# Generated by Django 5.1.15 on 2026-09-10 18:19

import django.core.validators
import django.db.models.deletion
import frota.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('especialidade', models.CharField(max_length=50, verbose_name='Especialidade')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10, verbose_name='Turno')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Mecânico',
                'verbose_name_plural': 'Mecânicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='A CNH deve conter apenas números (entre 9 e 11 dígitos).', regex='^\\d{9,11}$')], verbose_name='CNH')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('A', 'A - Motocicletas'), ('B', 'B - Carros'), ('AB', 'AB - Carros e motos'), ('C', 'C - Caminhões'), ('D', 'D - Ônibus'), ('E', 'E - Carretas/combinações')], max_length=2, verbose_name='Categoria')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Informe um telefone válido, ex.: (62) 99999-8888.', regex='^\\(?\\d{2}\\)?[\\s-]?9?\\d{4}-?\\d{4}$')], verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('fabricante', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor unitário (R$)')),
                ('qtd_estoque', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade em estoque')),
                ('estoque_minimo', models.IntegerField(default=5, help_text='Usado no relatório de Estoque Crítico.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque mínimo ideal')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Formato antigo ABC1234 ou Mercosul ABC1D23.', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Informe uma placa válida no padrão antigo (ABC1234) ou Mercosul (ABC1D23).', regex='^[A-Za-z]{3}-?\\d[A-Za-z0-9]\\d{2}$')], verbose_name='Placa')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), frota.models.validar_ano_nao_futuro_demais], verbose_name='Ano')),
                ('quilometragem', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quilometragem (km)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(validators=[frota.models.validar_data_nao_futura], verbose_name='Data')),
                ('tipo', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva')], max_length=15, verbose_name='Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição do serviço')),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='frota.mecanico', verbose_name='Mecânico responsável')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='frota.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ItemManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor unitário (R$)')),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='frota.manutencao')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_utilizados', to='frota.peca', verbose_name='Peça')),
            ],
            options={
                'verbose_name': 'Item da manutenção',
                'verbose_name_plural': 'Itens da manutenção',
            },
        ),
    ]
